title: Abel Soares Siqueira
email: abel.s.siqueira@gmail.com
baseurl: ""
url: "http://abelsiqueira.github.io" # the base hostname & protocol for your site
github_username:  abelsiqueira
markdown: kramdown
t:
  en:
    backto:  "back to"
    homeurl: "/home/"
    phd:     "Ph.D."
    master:  "Master"
    tcc:     "Term paper"
    intern:  "Internship"
  br:
    backto: "voltar para"
    homeurl:  "/"
    phd:     "Doutorado"
    master:  "Mestrado"
    tcc:     "TCC"
    intern:  "Iniciação Científica"
